version: '3.7'
services:
  app:
    container_name: tickets
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - app:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    container_name: tickets-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  app:
  db:

# Networks to be created to facilitate communication between containers
networks:
  postgres:
    driver: bridge
